### PR TITLE
Update OPEA API spec to 1.0 version

### PR DESCRIPTION
**Pull request by ftian1**

### CODE REVIEW

**Comment by ftian1** [comment]
@dbkinder pls be aware of this change which may impact the content in opea.github.io

**Review by kevinintel — APPROVED** [review]

**Review by dbkinder — COMMENTED** [review]
You changed the version number but there's no change to the contents. There are technical errors in the content that should be fixed.

**Comment by chickenrae** [comment]
Have @dbkinder 's comments been addressed?

**Comment by mkbhanda** [comment]
There were no additional commits since @dbkinder review and I do not know what the technical issues were. The two other files are binaries. @ftian1 would you please shed light or do we need to trouble @dbkinder in his retirement?

**Comment by ftian1** [comment]
@mkbhanda  @chickenrae  let me confirm with @dbkinder

**Review by yinghu5 — APPROVED** [review]
LGTM

**Pull request merged**
