### PR TITLE
add code owners

### PR DESCRIPTION
**Pull request by kevinintel**

### CODE REVIEW

**Review by hshen14 — APPROVED** [review]

**Review by chensuyue — APPROVED** [review]

**Review by dbkinder — CHANGES_REQUESTED** [review]
Should this table be incorporated into the repos as a CODEOWNERS file so it's enforced by GitHub?

**Review by ftian1 — APPROVED** [review]
looks like the first commit has some typos. pls fix it when merge

**Comment by kevinintel** [comment]
> Should this table be incorporated into the repos as a CODEOWNERS file so it's enforced by GitHub?

some github id can't be detected by CODEOWNERS, I suggest to use current file first

**Comment by kevinintel** [comment]
> looks like the first commit has some typos. pls fix it when merge

which one

**Comment by ftian1** [comment]
image
@kevinintel

**Comment by kevinintel** [comment]
> image @kevinintel

It can be removed when merging

**Pull request merged**
